### ISSUE TITLE
The if/else statement in docker does not work properly.

### ISSUE THREAD

**Issue by webbertakken** [Unity-CI/docker#33]
**Bug description**

The if/else statement in docker does not work properly.

Specifically: `editor/Dockerfile:15-21`

https://github.com/Unity-CI/docker/blob/566bfdc359d8dfd634f0dc9e32d24b1490a821d4/editor/Dockerfile#L15-L21

**How to reproduce**

Clone

```bash
git clone git@github.com:Unity-CI/docker.git
```

Checkout main

```bash
git checkout main
```

Build the container with `module=base` 

```bash
docker build --build-arg hubImage=unityci/hub:0.2.0 --build-arg baseImage=unityci/base:0.2.0 --build-arg version=2019.2.9f1 --build-arg changeSet=ebce4d76e6e8 --build-arg module=base editor -t editor-2019-2-9f1-base
```

or `module=mac-mono` 
```bash
docker build --build-arg hubImage=unityci/hub:0.2.0 --build-arg baseImage=unityci/base:0.2.0 --build-arg version=2019.2.9f1 --build-arg changeSet=ebce4d76e6e8 --build-arg module=mac-mono editor -t editor-2019-2-9f1-mac-mono
```

or `module=something-invalid`
```bash
docker build --build-arg hubImage=unityci/hub:0.2.0 --build-arg baseImage=unityci/base:0.2.0 --build-arg version=2019.2.9f1 --build-arg changeSet=ebce4d76e6e8 --build-arg module=invalid editor -t editor-2019-2-9f1-invalid
```

**Expected behavior**

The if else is not hard to read, so the intention is correct, but currently not working. If the if else works properly, the rest will start working again and images will start generating.

**Additional details**

This is currently a blocker for publishing all new images.

**Comment by jonathanperret** [comment]
The `[[` is a [bashism](https://mywiki.wooledge.org/Bashism#Conditionals) and in Ubuntu uses `dash` to run scripts by default. Switching to the standard `[` should fix the issue.

**Comment by webbertakken** [comment]
I tried that, but I don't think that worked either.

**Comment by jonathanperret** [comment]
Sorry, `[` expects `=` as an operator, not `==`.

**Comment by webbertakken** [comment]
That, I actually haven't tried :)
