### ISSUE TITLE
I need 2020.1.15f1 image

### ISSUE THREAD

**Issue by initfusion** [Unity-CI/docker#52]
**Description**

Please create an image for unity editor 2020.1.15f1.

**Comment by webbertakken** [comment]
As per the [docs](https://unity-ci.com/docs/unity-ci/docker-images) (third line); please allow a few hours for images to appear.

This image hasn't even been in Unity's news feed yet.

**Comment by initfusion** [comment]
Thanks @webbertakken 
Now I can see the image.
